### ISSUE TITLE
Placement of mouse cursor according to closest area to the gaze point

### ISSUE THREAD

**Issue by Hoodad** [dansav/vs-eye-tracking#1]
Hello and thanks for a great plugin!

I have a feature request that would place the cursor not on the line that the gaze point is over, but rather the line that is the closest to the gaze point. I have tried to illustrate the problem with the attached screenshot. 

Say I want to move the cursor to line 5 col ~90 it can be tricky to hit the exact line and the resulting location for the cursor would be drastically different if I succeeded or not.

![visual_studio_plugin](https://user-images.githubusercontent.com/232197/55800256-91aacd00-5ad3-11e9-97ac-de9b1583fbfc.png)

Expected behavior would be to have some logic that moves the cursor to the line and col that is the closest to the gaze point.

**Comment by dansav** [comment]
Thank you for your feature request. This would definitively improve the usefulness of the caret feature.

**Comment by dansav** [comment]
I have tried the new implementation for a couple of days, and while it is not perfect it is a great improvement over the first implementation. Will close this issue now.
