### ISSUE TITLE
Recommended hardware

### ISSUE THREAD

**Issue by LaraSQP** [dansav/vs-eye-tracking#10]
What kind of camera do you use for this? Regular webcam or perhaps with infrared? Eye tracker?

A specific recommendation of a camera would be appreciated so that I can evaluate your extension with it or alike products.

Thank you for taking the time to develop the extension and making it available for free.

**Comment by niklaskallander** [comment]
@LaraSQP I use this one: https://gaming.tobii.com/product/tobii-eye-tracker-4c/

The extension is using Tobii apis so I don’t think any other cameras/sensors are supported.

**Comment by LaraSQP** [comment]
Much appreciated.
