### ISSUE TITLE
Support multiple editor windows

### ISSUE THREAD

**Issue by Hnkee** [dansav/vs-eye-tracking#11]
When using multiple editor windows, docked next to each other, it would be nice if you could use dmove-carret-feature to move the cursor between the windows.

**Comment by dansav** [comment]
This is a great idea for a new feature! If it does not fit within the caret feature. Setting focus on a already visible window.

**Comment by dansav** [comment]
I am exploring this idea on a feature branch feature/window_focus. It requires a lot of more work, but I think it could be a really useful feature. It will support switching input focus between different document windows, but also setting focus on Solution Explorer and other tool windows.

**Comment by Hnkee** [comment]
Ok, that is good. It will also improve move carret feature with single window since you dont have to set focus to it manually every time you worked outside VS (like when using VS as editor for Unity, then it happens a lot.....)

**Comment by dansav** [comment]
I have made some progress on this now. Window focus and moving caret now works together. Now I just need a little more work on how scroll should work since I changed how the keyboard events are handled. Then I will merge the changes and push a new release.

**Comment by dansav** [comment]
I ran into an issue with keyboard event handlers not triggering when an XAML editor window/tab was active, so had to fix that. I have merged the code to develop branch, and will soon prepare a release.

**Comment by Hnkee** [comment]
Nice.

**Comment by dansav** [comment]
Version 0.4 has just been release: http://vsixgallery.com/extension/65bd244c-48a0-46af-953a-0fb433e5343d/

Please try it out and let me know what you think about the new Window Focus feature.
