### ISSUE TITLE
Create a custom UI for the options page

### ISSUE THREAD

**Issue by dansav** [dansav/vs-eye-tracking#9]
I have seen some code examples that use WinForms to create a custom UI. I would be more comfortable if it was possible to use WPF.

Some GUI ideas:
* Sliders for delay- and timeout-values (to help keep values within a sensible range)
* Show basic eye tracker status

**Comment by niklaskallander** [comment]
I know I've fiddled with something along the lines of: https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-wpf-composite-control-in-windows-forms to accomplish (long time ago). I remember it wasn't exactly perfect, but it might have been my lack-of-skill rather than anything else. (:

**Comment by dansav** [comment]
I have experimented a bit with how I think the custom UI should look, and this is what I have come up with:
![Custom Options Design proposal 1](https://user-images.githubusercontent.com/879869/65392593-d4f1b300-dd76-11e9-91b1-033a3b76098d.png)

Obviously it is what is in the blue rectangle that can be customized, and I did not spend too much time on the texts. Texts will probably evolve over time anyway, and I am thinking about adding some short descriptions for each feature

**Comment by dansav** [comment]
I just found out that there is a built in class in Visual Studio shell (UIElementDialogPage) that already handles the wrapping of WPF in a WinForms host control!

**Comment by dennyronngren** [comment]
That's great!

**Comment by dansav** [comment]
I have a very rough implementation on a branch: feature/options-gui.  Only the basic properties are there and I have not styled anything yet.

**Comment by dansav** [comment]
I just merged this #12 to the develop branch, and will hopefully do a release soon.

**Comment by dansav** [comment]
I have released version 0.5 with the new options GUI
